# Generated by Django 5.1.4 on 2024-12-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
