# Generated by Django 5.1.4 on 2024-12-29 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='added',
        ),
    ]
